package codigo;

/**
 *
 * @author mario
 */
public class VentanaCalculadora extends javax.swing.JFrame {

    double operando1 = 0;// guarda el primer numero que metamos
    String operacion = "";// guarda la operacion pulsada

    public VentanaCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pantalla = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jButtonigual = new javax.swing.JButton();
        jButtonsuma = new javax.swing.JButton();
        jButtonresta = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pantalla.setBackground(new java.awt.Color(0, 0, 0));
        pantalla.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        pantalla.setForeground(new java.awt.Color(51, 255, 51));
        pantalla.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pantalla.setText("0");
        pantalla.setOpaque(true);
        getContentPane().add(pantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 314, 50));

        jButton8.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 118, 64, 64));

        jButton7.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 64, 64));

        jButton9.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 118, 64, 64));

        jButton5.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 188, 64, 64));

        jButton4.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 64, 64));

        jButton6.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 188, 64, 64));

        jButton2.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 64, 64));

        jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 64, 64));

        jButton3.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 64, 64));

        jButton0.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jButton0.setText("0");
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 64, 64));

        jButtonigual.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jButtonigual.setText("=");
        jButtonigual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonigualActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonigual, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 140, 64));

        jButtonsuma.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jButtonsuma.setText("➕");
        jButtonsuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsumaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonsuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 118, 64, 64));

        jButtonresta.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jButtonresta.setText("➖");
        jButtonresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonrestaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonresta, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 188, 64, 64));

        jButton14.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jButton14.setText("➗");
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 64, 64));

        jButton15.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jButton15.setText("✖");
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 64, 64));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String auxiliar = pantalla.getText();
        if (auxiliar .equals("0")){
          pantalla.setText("8");
        }else {
            pantalla.setText(auxiliar + "8");
       }
      
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String auxiliar = pantalla.getText();
        if (auxiliar .equals("0")){
          pantalla.setText("7");
        }else {
            pantalla.setText(auxiliar + "7");
       }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String auxiliar = pantalla.getText();
        if (auxiliar .equals("0")){
          pantalla.setText("9");
        }else {
            pantalla.setText(auxiliar + "9");
       }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String auxiliar = pantalla.getText();
        if (auxiliar .equals("0")){
          pantalla.setText("5");
        }else {
            pantalla.setText(auxiliar + "5");
       }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       String auxiliar = pantalla.getText();
        if (auxiliar .equals("0")){
          pantalla.setText("4");
        }else {
            pantalla.setText(auxiliar + "4");
       }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
      String auxiliar = pantalla.getText();
        if (auxiliar .equals("0")){
          pantalla.setText("6");
        }else {
            pantalla.setText(auxiliar + "6");
       }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String auxiliar = pantalla.getText();
        if (auxiliar .equals("0")){
          pantalla.setText("2");
        }else {
            pantalla.setText(auxiliar + "2");
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      String auxiliar = pantalla.getText();
        if (auxiliar .equals("0")){
          pantalla.setText("1");
        }else {
            pantalla.setText(auxiliar + "1");
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       String auxiliar = pantalla.getText();
        if (auxiliar .equals("0")){
          pantalla.setText("3");
        }else {
            pantalla.setText(auxiliar + "3");
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
      String auxiliar = pantalla.getText();
        if (auxiliar .equals("0")){
          pantalla.setText("0");
        }else {
            pantalla.setText(auxiliar + "0");
       }
    }//GEN-LAST:event_jButton0ActionPerformed

    private void jButtonsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsumaActionPerformed
    operacion = "+";
    // Doble.valueof convierte un string en su equicalente numerico
    operando1 = Double.valueOf(pantalla.getText());
    //reseteo de pantalla
    pantalla.setText("0");
    }//GEN-LAST:event_jButtonsumaActionPerformed

    private void jButtonigualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonigualActionPerformed
        Double operando2 = Double.valueOf(pantalla.getText());
        if(operacion.equals("+")){
            operando1 = operando1 + operando2;
        }
        pantalla.setText(""+operando1);
    }//GEN-LAST:event_jButtonigualActionPerformed

    private void jButtonrestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonrestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonrestaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonigual;
    private javax.swing.JButton jButtonresta;
    private javax.swing.JButton jButtonsuma;
    private javax.swing.JLabel pantalla;
    // End of variables declaration//GEN-END:variables
}
